### ISSUE TITLE
fe / add authentication endpoints

### ISSUE THREAD

**Issue by struckchure** [Dev-47/quiz-app#16]

**Comment by dchief1** [comment]
### Authentication Endpoints

- [ ] Password-based authentication
- [ ] Multi-factor authentication (optional)
- [ ] Token-based authentication (optional, depends on what's needed though)

1. Password-based authentication
      - Passwords can be in the form of a string of letters, numbers, or special characters.

2. Multi-factor authentication (optional)
  - This requires two or more independent ways to identify a user. Examples include codes generated from the user’s 
     smartphone, Captcha tests, fingerprints, voice biometrics or facial recognition. 

3. Token-based authentication (optional, depends on what's needed though)
  - This would give admins extra flexibility to audit, monitor or extend many flows:

       extra business logic when a token is refresh (possible adding or removing scopes to the new access token)
       post client authentication when obtaining an access token (audit logging, monitoring)
       setting a specific token lifetime based on the context

**I don't know much about the project but hope this helps though **

**Comment by struckchure** [comment]
> ### Authentication Endpoints
> 
>     * [ ]  Password-based authentication
> 
>     * [ ]  Multi-factor authentication (optional)
> 
>     * [ ]  Token-based authentication (optional, depends on what's needed though)
> 
> 
>     1. Password-based authentication
>        
>        * Passwords can be in the form of a string of letters, numbers, or special characters.
> 
>     2. Multi-factor authentication (optional)
> 
> 
>     * This requires two or more independent ways to identify a user. Examples include codes generated from the user’s
>       smartphone, Captcha tests, fingerprints, voice biometrics or facial recognition.
> 
> 
>     3. Token-based authentication (optional, depends on what's needed though)
> 
> 
>     * This would give admins extra flexibility to audit, monitor or extend many flows:
>       extra business logic when a token is refresh (possible adding or removing scopes to the new access token)
>       post client authentication when obtaining an access token (audit logging, monitoring)
>       setting a specific token lifetime based on the context
> 
> 
> **I don't know much about the project but hope this helps though **

Huh, adding those authentications would be an overkill, let's keep it basic, just password-based authentication

**Comment by dchief1** [comment]
Ok , great 👍
