### ISSUE TITLE
fe / create timer components for quiz frontend

### ISSUE THREAD

**Issue by struckchure** [Dev-47/quiz-app#3]
No styling is necessary here, just funtionality

**Comment by ImArnoldDCODES** [comment]
https://www.codegrepper.com/search.php?q=countdown%20in%20react%20jshttps://www.codegrepper.com/search.php?q=countdown%20in%20react%20js

**Comment by Haryanfe** [comment]
Are you guys finished your own tasks?

**Comment by struckchure** [comment]
At the end, the timer should be used this way

```jsx
// Quiz.jsx or in any component
...
<Timer minutes={5} onFinish={()=>{console.log("time is up")}} />
...
```

taking 2 props
- minutes (the time allowed for the quiz, should be converted to seconds, depending on how the timer was build)
- onFinish (the function should be executed once the time counts to zero)

**Comment by struckchure** [comment]
Leave the timer for now !!!
