### ISSUE TITLE
fe / add index page + entry animation

### ISSUE THREAD

**Issue by struckchure** [Dev-47/quiz-app#40]
check [here](https://github.com/Dev-47/quiz-app/discussions/11#discussioncomment-1870306) for more in the animation

**Comment by ImArnoldDCODES** [comment]
😫😫😫👨‍💻

**Comment by struckchure** [comment]
> tired_facetired_facetired_faceman_technologist

:eyes:

**Comment by struckchure** [comment]
Check https://github.com/Dev-47/quiz-app/discussions/11#discussioncomment-1877974 for the web prototype, you should do the index page ASAP, the first page

**Comment by struckchure** [comment]
@ImArnoldDCODES Perfect!!!
