### ISSUE TITLE
fe / add quiz list page

### ISSUE THREAD

**Issue by struckchure** [Dev-47/quiz-app#51]
That is the quiz list page - https://xd.adobe.com/view/eff255b1-4d02-41cc-8159-0e941aa3ab29-baa1/screen/b15ee957-722f-40f2-b931-edf22665abc2

![Screenshot from 2021-12-28 09-30-08](https://user-images.githubusercontent.com/55154055/147545961-70b4ed94-d2e5-4d05-8223-0066db81217c.png)

Part to ignore
![Screenshot from 2021-12-28 09-27-26](https://user-images.githubusercontent.com/55154055/147545734-0e0523ab-1480-420c-9419-3b34f5df7fbc.png)

Ignore that part :point_up: , do only the right part

There's the base layout you should use, that way you can focus only on the contents on the quiz list page

**Comment by Horlakz** [comment]
fixed, kindly close this issue sir
