### ISSUE TITLE
fe / add page to start quiz

### ISSUE THREAD

**Issue by struckchure** [Dev-47/quiz-app#52]
The prototype is at https://xd.adobe.com/view/eff255b1-4d02-41cc-8159-0e941aa3ab29-baa1/screen/0cce846e-229a-477f-89bb-a9d937916204

pass a prop to the component, which will be the `quiz_id`, the quiz will be fetched from the backend when the component mounts, you can use a dummy data object

```js
{
  no_questions: 10,
  time: 90 // in minutes
}
```
and give `90` minutes, you'll have to convert it to something user-readable, like `1hr 30min`, or you can leave it as just `90 minutes`

**Comment by Horlakz** [comment]
this thing ehn.. it should be a component na, not a page
e con remain how them go click next and e go show another component

**Comment by Horlakz** [comment]
will the rules be fetched from the backend too

**Comment by Horlakz** [comment]
dust and dusted
