### ISSUE TITLE
fe / add quiz result page

### ISSUE THREAD

**Issue by struckchure** [Dev-47/quiz-app#53]
Here's the drill

https://xd.adobe.com/view/eff255b1-4d02-41cc-8159-0e941aa3ab29-baa1/screen/5f07be18-1db3-4018-8ea7-8613caee5c0a

This should also take in `quiz_id` as props

Check https://reactjs.org/docs/components-and-props.html for more on props

**Comment by struckchure** [comment]
@Horlakz will help you, should you need more insights

or you can find me too if necessary

**Comment by Horlakz** [comment]
@mjay0100 how far na

**Comment by Horlakz** [comment]
#71  it has been fixed, kindly close this issue sir
